package com.sportsschedule.gosenk.sportsscheduleandroid.splash;

import android.app.Activity;
import android.content.Intent;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.Handler;

import com.sportsschedule.gosenk.sportsscheduleandroid.R;
import com.sportsschedule.gosenk.sportsscheduleandroid.teams.TeamHolder;
import com.sportsschedule.gosenk.sportsscheduleandroid.teams.TeamsActivity;

public class SplashActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                new LoadTeams().execute();
            }
        }, 5000);

    }

    private class LoadTeams extends AsyncTask<String, Void, String> {
        @Override
        protected String doInBackground(String... params) {

            TeamHolder teamHolder = TeamHolder.getInstance();

            return null;
        }

        @Override
        protected void onPostExecute(String result) {
            Intent intent = new Intent(getApplicationContext(), TeamsActivity.class);
            startActivity(intent);
        }

        @Override
        protected void onPreExecute() {
        }

        @Override
        protected void onProgressUpdate(Void... values) {
        }
    }

}

/*

    #####  Color Palette by Paletton.com
    #####  Palette URL: http://paletton.com/#uid=13i0u0kllllaFw0g0qFqFg0w0aF


    *** Primary color:

       shade 0 = #226666 = rgb( 34,102,102) = rgba( 34,102,102,1) = rgb0(0.133,0.4,0.4)
       shade 1 = #669999 = rgb(102,153,153) = rgba(102,153,153,1) = rgb0(0.4,0.6,0.6)
       shade 2 = #407F7F = rgb( 64,127,127) = rgba( 64,127,127,1) = rgb0(0.251,0.498,0.498)
       shade 3 = #0D4D4D = rgb( 13, 77, 77) = rgba( 13, 77, 77,1) = rgb0(0.051,0.302,0.302)
       shade 4 = #003333 = rgb(  0, 51, 51) = rgba(  0, 51, 51,1) = rgb0(0,0.2,0.2)


    #####  Generated by Paletton.com (c) 2002-2014

 */
